FROM ubuntu:22.04

COPY ./dist/tahoe /bin/tahoe

RUN tahoe --version;

RUN \
  cd /root; \
  mkdir /root/.tahoe-client; \
  mkdir /root/.tahoe-introducer; \
  mkdir /root/.tahoe-node;

RUN tahoe create-introducer --location=tcp:introducer:3458 --port=tcp:3458 /root/.tahoe-introducer
RUN tahoe start /root/.tahoe-introducer
RUN tahoe create-node --location=tcp:server:3457 --port=tcp:3457 --introducer=$(cat /root/.tahoe-introducer/private/introducer.furl) /root/.tahoe-node
RUN tahoe create-client --webport=3456 --introducer=$(cat /root/.tahoe-introducer/private/introducer.furl) --basedir=/root/.tahoe-client --shares-needed=1 --shares-happy=1 --shares-total=1

VOLUME ["/root/.tahoe-client", "/root/.tahoe-node", "/root/.tahoe-introducer"]
EXPOSE 3456 3457 3458
ENTRYPOINT ["/bin/tahoe"]
CMD []